#!/bin/bash

## ===== General environment variables for the Percona Operator tests =====
export OPERATOR_ROOT_PATH=${OPERATOR_ROOT_PATH:-${PWD}}
echo "OPERATOR_ROOT_PATH=${OPERATOR_ROOT_PATH}"

export PERCONA_VERSION_SERVICE_URL=${PERCONA_VERSION_SERVICE_URL:-"https://check-dev.percona.com/versions/v1"}
echo "PERCONA_VERSION_SERVICE_URL=${PERCONA_VERSION_SERVICE_URL}"

## ======= Upstream DB operators params for testing ===============
export PXC_OPERATOR_VERSION=${PXC_OPERATOR_VERSION:-"1.18.0"}
echo "PXC_OPERATOR_VERSION=${PXC_OPERATOR_VERSION}"

export PXC_DB_ENGINE_VERSION=${PXC_DB_ENGINE_VERSION:-"8.0.42-33.1"}
echo "PXC_DB_ENGINE_VERSION=${PXC_DB_ENGINE_VERSION}"

# Recommended DB engine version available in PREVIOUS_PXC_OPERATOR_VERSION
export PREVIOUS_PXC_DB_ENGINE_VERSION=${PREVIOUS_PXC_DB_ENGINE_VERSION:-"8.0.41-32.1"}
echo "PREVIOUS_PXC_DB_ENGINE_VERSION=${PREVIOUS_PXC_DB_ENGINE_VERSION}"

export PSMDB_OPERATOR_VERSION=${PSMDB_OPERATOR_VERSION:-"1.21.1"}
echo "PSMDB_OPERATOR_VERSION=${PSMDB_OPERATOR_VERSION}"

export PSMDB_DB_ENGINE_VERSION=${PSMDB_DB_ENGINE_VERSION:-"8.0.12-4"}
echo "PSMDB_DB_ENGINE_VERSION=${PSMDB_DB_ENGINE_VERSION}"

# Recommended DB engine version available in PREVIOUS_PSMDB_OPERATOR_VERSION
export PREVIOUS_PSMDB_DB_ENGINE_VERSION=${PREVIOUS_PSMDB_DB_ENGINE_VERSION:-"7.0.15-9"}
echo "PREVIOUS_PSMDB_DB_ENGINE_VERSION=${PREVIOUS_PSMDB_DB_ENGINE_VERSION}"

export PG_OPERATOR_VERSION=${PG_OPERATOR_VERSION:-"2.7.0"}
echo "PG_OPERATOR_VERSION=${PG_OPERATOR_VERSION}"

export PG_DB_ENGINE_VERSION=${PG_DB_ENGINE_VERSION:-"17.5.2"}
echo "PG_DB_ENGINE_VERSION=${PG_DB_ENGINE_VERSION}"

# Recommended DB engine version available in PREVIOUS_PG_OPERATOR_VERSION
export PREVIOUS_PG_DB_ENGINE_VERSION=${PREVIOUS_PG_DB_ENGINE_VERSION:-"17.4"}
echo "PREVIOUS_PG_DB_ENGINE_VERSION=${PREVIOUS_PG_DB_ENGINE_VERSION}"

# Previous versions of the operators for testing upstream DB operators upgrades.
export PREVIOUS_PG_OPERATOR_VERSION=${PREVIOUS_PG_OPERATOR_VERSION:-"2.6.0"}
echo "PREVIOUS_PG_OPERATOR_VERSION=${PREVIOUS_PG_OPERATOR_VERSION}"

export PREVIOUS_PXC_OPERATOR_VERSION=${PREVIOUS_PXC_OPERATOR_VERSION:-"1.17.0"}
echo "PREVIOUS_PXC_OPERATOR_VERSION=${PREVIOUS_PXC_OPERATOR_VERSION}"

export PREVIOUS_PSMDB_OPERATOR_VERSION=${PREVIOUS_PSMDB_OPERATOR_VERSION:-"1.19.1"}
echo "PREVIOUS_PSMDB_OPERATOR_VERSION=${PREVIOUS_PSMDB_OPERATOR_VERSION}"

## ============== K3D cluster configuration ===================
export KUBECONFIG="${KUBECONFIG:-${OPERATOR_ROOT_PATH}/test/kubeconfig}"
echo "KUBECONFIG=${KUBECONFIG}"
