---
version: "2"
linters:
  default: all
  disable:
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomoddirectives
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          deny:
            - pkg: github.com/pkg/errors
              desc: use 'errors' instead
            - pkg: github.com/gogo/protobuf/proto
              desc: use 'github.com/golang/protobuf/proto' instead
            - pkg: github.com/percona/go-mysql/log/slow
              desc: use only forked parser
            - pkg: gopkg.in/yaml.v2
              desc: use 'gopkg.in/yaml.v3' instead
    exhaustive:
      default-signifies-exhaustive: true
    godot:
      capital: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github.com/charmbracelet/bubbletea.Model
    lll:
      line-length: 170
      tab-width: 4
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: ""
          xml: camel
          yaml: ""
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - gocognit
          - lll
          - testpackage
          - unused
        path: _test\.go
      - path: (.+)\.go$
        text: 'G104: Errors unhandled'
      - path: (.+)\.go$
        text: exported method `.+` should have comment or be unexported
      - path: (.+)\.go$
        text: comment on exported method `.+` should be of the form `.+ ...`
      - path: (.+)\.go$
        text: exported method .+ returns unexported type .+, which can be annoying to use
    paths:
      - api/v1alpha1/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/percona/everest-operator)
    goimports:
      local-prefixes:
        - github.com/percona/everest-operator
  exclusions:
    generated: lax
    paths:
      - api/v1alpha1/
      - third_party$
      - builtin$
      - examples$
