---
runner:
  golangci-lint:
    cmd: go tool golangci-lint run --config=./.golangci.yml --issues-exit-code=0 --new-from-rev=$(git merge-base main HEAD) --fix
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    level: warning
