---
runner:
  golangci-lint:
    cmd: go tool golangci-lint run --config=./.golangci.yml --issues-exit-code=0 --new-from-merge-base $(git merge-base origin/main HEAD)
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    level: warning
