apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: YOUR_ACCESS_KEY_ID_BASE64_ENCODED
  AWS_SECRET_ACCESS_KEY: YOUR_SECRET_ACCESS_KEY_BASE64_ENCODED
kind: Secret
metadata:
  name: my-s3-backup-storage
type: Opaque
---
apiVersion: everest.percona.com/v1alpha1
kind: BackupStorage
metadata:
  name: my-s3-backup-storage
spec:
  bucket: my-s3-bucket
  credentialsSecretName: my-s3-backup-storage
  description: My S3 backup storage
  endpointURL: https://my-s3-endpoint.com
  forcePathStyle: false
  region: us-west-2
  type: s3
  verifyTLS: true
