apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: <YOUR BASE64 ENCODED KEY>
  AWS_ACCESS_KEY_ID: <YOUR BASE64 ENCODED ID>
---
apiVersion: everest.percona.com/v1alpha1
kind: BackupStorage
metadata:
  name: my-backup-storage
spec:
  type: s3
  bucket: "my-backup-bucket"
  region: "us-east-1"
  credentialsSecretName: "backup-credentials"