apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  labels:
    clusterName: mongodb-sharded
  name: mongodb-sharded
spec:
  backup:
    pitr:
      enabled: false
    schedules:
    - backupStorageName: my-s3-backup-storage
      enabled: true
      name: my-schedule
      schedule: 30 19 * * *
  engine:
    replicas: 3
    resources:
      cpu: "1"
      memory: 4G
    storage:
      class: standard-rwo
      size: 25Gi
    type: psmdb
    userSecretsName: everest-secrets-mongodb-sharded
    version: 8.0.12-4
  monitoring:
    resources: {}
  proxy:
    expose:
      type: internal
    replicas: 3
    resources:
      cpu: "1"
      memory: 2G
    type: mongos
  sharding:
    configServer:
      replicas: 3
    enabled: true
    shards: 2
