apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "everest.percona.com/v1alpha1",
          "kind": "BackupStorage",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "everest-operator"
            },
            "name": "backupstorage-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "everest.percona.com/v1alpha1",
          "kind": "DatabaseCluster",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "everest-operator"
            },
            "name": "databasecluster-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "everest.percona.com/v1alpha1",
          "kind": "DatabaseClusterBackup",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "everest-operator"
            },
            "name": "databaseclusterbackup-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "everest.percona.com/v1alpha1",
          "kind": "DatabaseClusterRestore",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "everest-operator"
            },
            "name": "databaseclusterrestore-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "everest.percona.com/v1alpha1",
          "kind": "DatabaseEngine",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "everest-operator"
            },
            "name": "databaseengine-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "everest.percona.com/v1alpha1",
          "kind": "MonitoringConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "everest-operator"
            },
            "name": "monitoringconfig-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-08-05T14:24:21Z"
    operators.operatorframework.io/builder: operator-sdk-v1.40.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: everest-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: BackupStorage is the Schema for the backupstorages API.
      displayName: Backup Storage
      kind: BackupStorage
      name: backupstorages.everest.percona.com
      version: v1alpha1
    - description: DatabaseClusterBackup is the Schema for the databaseclusterbackups
        API.
      displayName: Database Cluster Backup
      kind: DatabaseClusterBackup
      name: databaseclusterbackups.everest.percona.com
      version: v1alpha1
    - description: DatabaseClusterRestore is the Schema for the databaseclusterrestores
        API.
      displayName: Database Cluster Restore
      kind: DatabaseClusterRestore
      name: databaseclusterrestores.everest.percona.com
      version: v1alpha1
    - description: DatabaseCluster is the Schema for the databaseclusters API.
      displayName: Database Cluster
      kind: DatabaseCluster
      name: databaseclusters.everest.percona.com
      version: v1alpha1
    - description: DatabaseEngine is the Schema for the databaseengines API.
      displayName: Database Engine
      kind: DatabaseEngine
      name: databaseengines.everest.percona.com
      version: v1alpha1
    - kind: DataImporter
      name: dataimporters.everest.percona.com
      version: v1alpha1
    - kind: DataImportJob
      name: dataimportjobs.everest.percona.com
      version: v1alpha1
    - kind: LoadBalancerConfig
      name: loadbalancerconfigs.everest.percona.com
      version: v1alpha1
    - description: MonitoringConfig is the Schema for the monitoringconfigs API.
      displayName: Monitoring Config
      kind: MonitoringConfig
      name: monitoringconfigs.everest.percona.com
      version: v1alpha1
    - kind: PodSchedulingPolicy
      name: podschedulingpolicies.everest.percona.com
      version: v1alpha1
  description: Deploy database clusters easily with Everest operator
  displayName: Everest operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - statefulsets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - everest.percona.com
          resources:
          - backupstorages
          - databaseclusterbackups
          - databaseclusterrestores
          - databaseclusters
          - databaseengines
          - dataimportjobs
          - loadbalancerconfigs
          - monitoringconfigs
          - podschedulingpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - everest.percona.com
          resources:
          - backupstorages/finalizers
          - databaseclusterbackups/finalizers
          - databaseclusterrestores/finalizers
          - databaseclusters/finalizers
          - databaseengines/finalizers
          - dataimportjobs/finalizers
          verbs:
          - update
        - apiGroups:
          - everest.percona.com
          resources:
          - backupstorages/status
          - databaseclusterbackups/status
          - databaseclusterrestores/status
          - databaseclusters/status
          - databaseengines/status
          - dataimportjobs/status
          - loadbalancerconfigs/status
          - monitoringconfigs/status
          - podschedulingpolicies/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - everest.percona.com
          resources:
          - dataimporters
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - operator.victoriametrics.com
          resources:
          - vmagents
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - clusterserviceversions
          - installplans
          verbs:
          - get
          - list
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - pgv2.percona.com
          resources:
          - perconapgbackups
          - perconapgclusters
          - perconapgrestores
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - postgres-operator.crunchydata.com
          resources:
          - postgresclusters
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - psmdb.percona.com
          resources:
          - perconaservermongodbbackups
          - perconaservermongodbrestores
          - perconaservermongodbs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pxc.percona.com
          resources:
          - perconaxtradbclusterbackups
          - perconaxtradbclusterrestores
          - perconaxtradbclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - roles
          verbs:
          - bind
          - create
          - delete
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: everest-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: everest-operator
          control-plane: controller-manager
        name: everest-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
                command:
                - /manager
                env:
                - name: SYSTEM_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                image: docker.io/perconalab/everest-operator:0.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: webhook-certs
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: everest-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: webhook-certs
                secret:
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: everest-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - everest
  - dbaas
  - percona
  links:
  - name: Everest Operator
    url: https://everest-operator.domain
  maintainers:
  - email: diogo.recharte@percona.com
    name: diogo-recharte
  - email: mayank.shah@percona.com
    name: mayank-shah
  - email: oksana.grishchenko@percona.com
    name: oksana-grishchenko
  - email: michal.kralik@percona.com
    name: michal-kralik
  maturity: alpha
  provider:
    name: Percona
    url: https://percona.com
  version: 0.0.0
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: everest-operator-controller-manager
    failurePolicy: Fail
    generateName: mdatabasecluster-v1alpha1.everest.percona.com
    rules:
    - apiGroups:
      - everest.percona.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - databaseclusters
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-everest-percona-com-v1alpha1-databasecluster
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: everest-operator-controller-manager
    failurePolicy: Fail
    generateName: mdataimportjobs-v1akpha1.everest.percona.com
    rules:
    - apiGroups:
      - everest.percona.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - dataimportjobs
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-everest-percona-com-v1alpha1-dataimportjob
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: everest-operator-controller-manager
    failurePolicy: Fail
    generateName: vdatabasecluster-v1alpha1.everest.percona.com
    rules:
    - apiGroups:
      - everest.percona.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - databaseclusters
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-everest-percona-com-v1alpha1-databasecluster
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: everest-operator-controller-manager
    failurePolicy: Fail
    generateName: vmonitoringconfig-v1alpha1.everest.percona.com
    rules:
    - apiGroups:
      - everest.percona.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - monitoringconfigs
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-everest-percona-com-v1alpha1-monitoringconfig
