#!/bin/bash

export OPERATOR_ROOT_PATH=${OPERATOR_ROOT_PATH:-${PWD}}
echo "OPERATOR_ROOT_PATH=${OPERATOR_ROOT_PATH}"

export PXC_OPERATOR_VERSION=${PXC_OPERATOR_VERSION:-"1.17.0"}
echo "PXC_OPERATOR_VERSION=${PXC_OPERATOR_VERSION}"

export PXC_DB_ENGINE_VERSION=${PXC_DB_ENGINE_VERSION:-"8.0.41-32.1"}
echo "PXC_DB_ENGINE_VERSION=${PXC_DB_ENGINE_VERSION}"

export PSMDB_OPERATOR_VERSION=${PSMDB_OPERATOR_VERSION:-"1.20.1"}
echo "PSMDB_OPERATOR_VERSION=${PSMDB_OPERATOR_VERSION}"

export PSMDB_DB_ENGINE_VERSION=${PSMDB_DB_ENGINE_VERSION:-"7.0.18-11"}
echo "PSMDB_DB_ENGINE_VERSION=${PSMDB_DB_ENGINE_VERSION}"

export PG_OPERATOR_VERSION=${PG_OPERATOR_VERSION:-"2.6.0"}
echo "PG_OPERATOR_VERSION=${PG_OPERATOR_VERSION}"

export PG_DB_ENGINE_VERSION=${PG_DB_ENGINE_VERSION:-"17.4"}
echo "PG_DB_ENGINE_VERSION=${PG_DB_ENGINE_VERSION}"

export PERCONA_VERSION_SERVICE_URL=${PERCONA_VERSION_SERVICE_URL:-"https://check-dev.percona.com/versions/v1"}
echo "PERCONA_VERSION_SERVICE_URL=${PERCONA_VERSION_SERVICE_URL}"

export PREVIOUS_PG_OPERATOR_VERSION=${PREVIOUS_PG_OPERATOR_VERSION:-"2.5.0"}
echo "PREVIOUS_PG_OPERATOR_VERSION=${PREVIOUS_PG_OPERATOR_VERSION}"

export PREVIOUS_PXC_OPERATOR_VERSION=${PREVIOUS_PXC_OPERATOR_VERSION:-"1.16.1"}
echo "PREVIOUS_PXC_OPERATOR_VERSION=${PREVIOUS_PXC_OPERATOR_VERSION}"

export PREVIOUS_PSMDB_OPERATOR_VERSION=${PREVIOUS_PSMDB_OPERATOR_VERSION:-"1.19.1"}
echo "PREVIOUS_PSMDB_OPERATOR_VERSION=${PREVIOUS_PSMDB_OPERATOR_VERSION}"
