# permissions for end users to edit databaseclusterrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databaseclusterrestore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: everest-operator
    app.kubernetes.io/part-of: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseclusterrestore-editor-role
rules:
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusterrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - databaseclusterrestores/status
  verbs:
  - get
