# permissions for end users to view monitoringconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: monitoringconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: everest-operator
    app.kubernetes.io/part-of: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: monitoringconfig-viewer-role
rules:
- apiGroups:
  - everest.percona.com
  resources:
  - monitoringconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - everest.percona.com
  resources:
  - monitoringconfigs/status
  verbs:
  - get
