# permissions for end users to edit podschedulingpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: podschedulingpolicy-editor-role
rules:
  - apiGroups:
      - everest.percona.com
    resources:
      - podschedulingpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
