# permissions for end users to view podschedulingpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: everest-operator
    app.kubernetes.io/managed-by: kustomize
  name: podschedulingpolicy-viewer-role
rules:
  - apiGroups:
      - everest.percona.com
    resources:
      - podschedulingpolicies
    verbs:
      - get
      - list
      - watch
