apiVersion: everest.percona.com/v1alpha1
kind: MonitoringConfig
metadata:
  labels:
    app.kubernetes.io/name: monitoringconfig
    app.kubernetes.io/instance: monitoringconfig-sample
    app.kubernetes.io/part-of: everest-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: everest-operator
  name: monitoringconfig-sample
spec:
  # TODO(user): Add fields here
