apiVersion: everest.percona.com/v1alpha1
kind: DatabaseClusterBackup
metadata:
  labels:
    app.kubernetes.io/name: databaseclusterbackup
    app.kubernetes.io/instance: databaseclusterbackup-sample
    app.kubernetes.io/part-of: everest-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: everest-operator
  name: databaseclusterbackup-sample
spec:
  # TODO(user): Add fields here
