apiVersion: everest.percona.com/v1alpha1
kind: MonitoringConfig
metadata:
  labels:
    app.kubernetes.io/name: monitoringconfig
    app.kubernetes.io/instance: monitoringconfig-sample
    app.kubernetes.io/part-of: everest-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: everest-operator
  name: monitoringconfig-sample
spec:
  type: pmm
  credentialsSecretName: my-secret-name
  resources:
    limits:
      cpu: "300m"
      memory: "0.5G"
  pmm:
    url: http://localhost
    image: percona/pmm-client:latest

