//go:build !ignore_autogenerated

// everest-operator
// Copyright (C) 2022 Percona LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonDNSConfig) DeepCopyInto(out *SplitHorizonDNSConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonDNSConfig.
func (in *SplitHorizonDNSConfig) DeepCopy() *SplitHorizonDNSConfig {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplitHorizonDNSConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonDNSConfigList) DeepCopyInto(out *SplitHorizonDNSConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SplitHorizonDNSConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonDNSConfigList.
func (in *SplitHorizonDNSConfigList) DeepCopy() *SplitHorizonDNSConfigList {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonDNSConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplitHorizonDNSConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonDNSConfigSpec) DeepCopyInto(out *SplitHorizonDNSConfigSpec) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonDNSConfigSpec.
func (in *SplitHorizonDNSConfigSpec) DeepCopy() *SplitHorizonDNSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonDNSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonDNSConfigStatus) DeepCopyInto(out *SplitHorizonDNSConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonDNSConfigStatus.
func (in *SplitHorizonDNSConfigStatus) DeepCopy() *SplitHorizonDNSConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonDNSConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonDNSConfigTLSCertificateSpec) DeepCopyInto(out *SplitHorizonDNSConfigTLSCertificateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonDNSConfigTLSCertificateSpec.
func (in *SplitHorizonDNSConfigTLSCertificateSpec) DeepCopy() *SplitHorizonDNSConfigTLSCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonDNSConfigTLSCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonDNSConfigTLSSpec) DeepCopyInto(out *SplitHorizonDNSConfigTLSSpec) {
	*out = *in
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(SplitHorizonDNSConfigTLSCertificateSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonDNSConfigTLSSpec.
func (in *SplitHorizonDNSConfigTLSSpec) DeepCopy() *SplitHorizonDNSConfigTLSSpec {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonDNSConfigTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonDomain) DeepCopyInto(out *SplitHorizonDomain) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonDomain.
func (in *SplitHorizonDomain) DeepCopy() *SplitHorizonDomain {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitHorizonStatus) DeepCopyInto(out *SplitHorizonStatus) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]SplitHorizonDomain, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitHorizonStatus.
func (in *SplitHorizonStatus) DeepCopy() *SplitHorizonStatus {
	if in == nil {
		return nil
	}
	out := new(SplitHorizonStatus)
	in.DeepCopyInto(out)
	return out
}
